# Generated by Django 4.0.5 on 2022-06-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_empgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empgroup',
            old_name='alias',
            new_name='under',
        ),
    ]
