# Generated by Django 4.0.5 on 2022-06-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_alias_empgroup_under'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empgroup',
            old_name='under',
            new_name='alias',
        ),
    ]
