# Generated by Django 4.0.5 on 2022-07-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_empgroup2'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_VoucherModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('voucher_type', models.CharField(max_length=225)),
                ('abbreviation', models.CharField(max_length=225)),
                ('active_this_voucher_type', models.CharField(max_length=225)),
                ('method_voucher_numbering', models.CharField(max_length=225)),
                ('use_adv_conf', models.CharField(blank=True, max_length=225)),
                ('prvnt_duplictes', models.CharField(blank=True, default='Null', max_length=225)),
                ('use_effective_date', models.CharField(default='Null', max_length=225)),
                ('allow_zero_value_trns', models.CharField(max_length=225)),
                ('allow_naration_in_voucher', models.CharField(max_length=225)),
                ('make_optional', models.CharField(max_length=225)),
                ('provide_naration', models.CharField(max_length=225)),
                ('print_voucher', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('date_join', models.DateField()),
                ('defn_sal', models.CharField(max_length=225)),
                ('emp_name', models.CharField(max_length=225)),
                ('emp_desg', models.CharField(max_length=225)),
                ('fnctn', models.CharField(max_length=225)),
                ('location', models.CharField(max_length=225)),
                ('gender', models.CharField(max_length=225)),
                ('dob', models.DateField()),
                ('blood', models.CharField(max_length=225)),
                ('parent_name', models.CharField(max_length=225)),
                ('spouse_name', models.CharField(max_length=225)),
                ('address', models.CharField(max_length=225)),
                ('number', models.CharField(max_length=225)),
                ('emailid', models.CharField(max_length=225)),
                ('inc_tax_no', models.CharField(max_length=225)),
                ('aadhar_no', models.CharField(max_length=225)),
                ('uan', models.CharField(max_length=225)),
                ('pfn', models.CharField(max_length=225)),
                ('pran', models.CharField(max_length=225)),
                ('esin', models.CharField(max_length=225)),
                ('bankdtls', models.CharField(max_length=225)),
            ],
        ),
    ]
