# Generated by Django 4.0.5 on 2022-07-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_create_vouchermodels_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('alias', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('type', models.CharField(max_length=225)),
            ],
        ),
    ]
