# Generated by Django 4.0.5 on 2022-07-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_create_attendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='pan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax', models.IntegerField(max_length=225)),
                ('no', models.IntegerField(max_length=225)),
            ],
        ),
    ]
