# Generated by Django 4.0.5 on 2022-07-25 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_emailid_employee_email_e_found_trasfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.empgroup2'),
        ),
    ]
