# Generated by Django 4.0.5 on 2022-08-04 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='salary',
        ),
    ]
