# Generated by Django 4.0.5 on 2022-08-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('under', models.CharField(max_length=225)),
                ('effective', models.CharField(max_length=225)),
                ('payhead', models.CharField(max_length=225)),
                ('rate', models.CharField(max_length=225)),
                ('per', models.CharField(max_length=225)),
                ('payheaad_type', models.CharField(max_length=225)),
                ('calculation_type', models.CharField(max_length=225)),
            ],
        ),
    ]
