# Generated by Django 4.0.5 on 2022-09-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_create_employeegroup_emp_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_cost_default',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('revenue', models.CharField(blank=True, max_length=50, null=True)),
                ('non_revenue', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
